### ISSUE TITLE
Cannot see the text linked with 1.4.1

### ISSUE THREAD

**Issue by karibuTW** [Sommerregen/grav-plugin-external-links#23] opened 2018-03-12 01:23 UTC
Hello,
With the version 1.4.1, the text that has the link is not being displayed.

Anyone having the same issue?

Thank you

**Comment by Sommerregen** [comment] 2018-03-20 18:41
Hi @karibuTW , your version is outdated. Please update External Links to *v1.6.0*. You may experience a cache issue with v1.4.1 that was fixed in v1.4.3.

Please report back, if your issue still persists and also paste the markdown text with the link, that doesn't work.

**Comment by karibuTW** [comment] 2018-03-20 23:55
Thanks for the update.
At the moment I am doing all updates through the admin panel. The 1.4.3 has not be released yet there.
I'll let you know if it fixes or not in my case.

Thank you

**Comment by Sommerregen** [comment] 2018-03-21 18:57
Hey @karibuTW ,

That's strange. On the getgrav.org side external links is listed with version *v1.6.0*. Thus, it must appear in your admin panel, too. Can you check whether this is a caching issue (deleting the cache via admin and click on update again)? Otherwise I suggest you to open an issue for the admin plugin, https://github.com/getgrav/grav-plugin-admin/issues .

**Comment by karibuTW** [comment] 2018-03-21 23:27
Hello,
I'm using the admin panel 1.7.1 and I do have the external links listed with version 1.6.0.
But as soon as I enable it, I'm loosing links.

The markdown is pretty simple:
`[Speedtest](https://github.com/adolfintel/speedtest) is a HTML5 self-hosted speedtest that can be installed easily on your server.`
If I enable the plugin the word Speedtest will disappear.

Thanks
EDIT: Just updated to the 1.4.2, but no improvement.

**Comment by Sommerregen** [comment] 2018-03-28 16:39
Dear @karibuTW, I tested your markdown locally against *v1.6.0*, with and without cache enabled. But can't reproduce your issue. However I'm still on an older Grav version, *v1.4.0-rc.1* just to say. Maybe the latest releases changed something dramatically causing your problem.

**Comment by Sommerregen** [comment] 2018-07-12 18:17
Closing due to inactivity and reproducibility.

**Closed as completed by Sommerregen** 2018-07-12 18:17 UTC
Labels: question, cannot reproduce

**Comment by ghost** [comment] 2021-10-31 06:22
I have the same problem. Latest versions. I think the plugin isn't maintained anymore?
